name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: Lint Golang
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: false

      - name: Lint Golang
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: --timeout=30m
