// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePermission = "permission"

// Permission mapped from table <permission>
type Permission struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Type string `gorm:"column:type" json:"type"`
	Name string `gorm:"column:name" json:"name"`
}

// TableName Permission's table name
func (*Permission) TableName() string {
	return TableNamePermission
}
