// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID                int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // ID
	FullName          string    `gorm:"column:full_name" json:"full_name"`                 // username
	Avatar            string    `gorm:"column:avatar" json:"avatar"`                       // avator
	Password          string    `gorm:"column:password" json:"password"`                   // password
	Password2         string    `gorm:"column:password2" json:"password2"`                 // password 2
	Email             string    `gorm:"column:email" json:"email"`                         // email
	EmailVerified     bool      `gorm:"column:email_verified;not null" json:"email_verified"`
	ReceiveMarketing  bool      `gorm:"column:receive_marketing;not null;default:1" json:"receive_marketing"`
	Phone             string    `gorm:"column:phone" json:"phone"` // phone
	PhoneVerified     bool      `gorm:"column:phone_verified;not null" json:"phone_verified"`
	Status            int32     `gorm:"column:status" json:"status"`         // 0: disable,1: normal,2: forbidden
	CreatedAt         time.Time `gorm:"column:created_at" json:"created_at"` // Created DateTime
	UpdatedAt         time.Time `gorm:"column:updated_at" json:"updated_at"` // Updated DateTime
	RoleID            int32     `gorm:"column:role_id;not null" json:"role_id"`
	CompanyID         int32     `gorm:"column:company_id" json:"company_id"`
	DateOfBirth       time.Time `gorm:"column:date_of_birth" json:"date_of_birth"`
	Gender            string    `gorm:"column:gender" json:"gender"`
	FcmToken          string    `gorm:"column:fcm_token" json:"fcm_token"`
	FcmTokenTimestamp time.Time `gorm:"column:fcm_token_timestamp" json:"fcm_token_timestamp"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
